#!/usr/bin/env python3
"""Resolve build/release versions for packaged GitHub Actions builds."""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
RELEASE_RUNTIME_PATH = REPO_ROOT / "game" / "release_runtime.py"


def _read_source_version():
    text = RELEASE_RUNTIME_PATH.read_text(encoding="utf-8")
    match = re.search(r'^GAME_VERSION\s*=\s*"([^"]+)"', text, flags=re.MULTILINE)
    if not match:
        raise RuntimeError("Could not find GAME_VERSION in game/release_runtime.py")
    return match.group(1).strip()


def _normalize_manual_version(value):
    text = str(value or "").strip()
    return text[1:] if text.startswith("v") else text


def _unstable_tick_version(source_version, run_number):
    run_text = re.sub(r"\D+", "", str(run_number or "").strip())
    if not run_text:
        run_text = "0"
    match = re.match(r"^v?(\d+)\.(\d+)\.(\d+)(.*)$", str(source_version or "").strip())
    if not match:
        return f"{source_version}.unstable.{run_text}"
    major, middle, _patch, suffix = match.groups()
    if not suffix:
        suffix = "-unstable"
    return f"{major}.{middle}.{run_text}{suffix}"


def resolve_build_version(env=None):
    env = os.environ if env is None else env
    source_version = _read_source_version()
    manual_version = _normalize_manual_version(env.get("BAKERRRR_RELEASE_VERSION"))
    event_name = str(env.get("GITHUB_EVENT_NAME", "") or "").strip().lower()
    if manual_version:
        version = manual_version
        channel = "manual"
    elif event_name == "push":
        version = _unstable_tick_version(source_version, env.get("GITHUB_RUN_NUMBER"))
        channel = "unstable"
    else:
        version = source_version
        channel = "source"

    run_number = str(env.get("GITHUB_RUN_NUMBER", "") or "").strip()
    sha = str(env.get("GITHUB_SHA", "") or "").strip()[:7]
    label_bits = [channel]
    if run_number:
        label_bits.append(f"run.{run_number}")
    if sha:
        label_bits.append(sha)
    return {
        "source_version": source_version,
        "version": version,
        "tag": version if version.startswith("v") else f"v{version}",
        "label": ".".join(label_bits),
        "channel": channel,
    }


def write_runtime_hook(path, build):
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(
        "\n".join(
            (
                '"""Generated by build_tools/resolve_build_version.py."""',
                "",
                "import os",
                "",
                f"os.environ.setdefault('BAKERRRR_BUILD_VERSION', {build['version']!r})",
                f"os.environ.setdefault('BAKERRRR_BUILD_LABEL', {build['label']!r})",
                "",
            )
        ),
        encoding="utf-8",
    )


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-runtime-hook", help="Write a PyInstaller runtime hook that stamps the resolved version.")
    parser.add_argument("--print-env", action="store_true", help="Print shell-style version fields.")
    args = parser.parse_args(argv)
    build = resolve_build_version()
    if args.write_runtime_hook:
        write_runtime_hook(args.write_runtime_hook, build)
    if args.print_env:
        for key in ("source_version", "version", "tag", "label", "channel"):
            print(f"{key.upper()}={build[key]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
